name: Scraper BIEN ICI
on:
  schedule:
    #- cron: '0 15 * * *'  # 15h UTC = 17h Paris (UTC+2 en été)
  workflow_dispatch:     # Permet aussi de le lancer manuellement

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Exécuter le scraper
        run: |
          python main.py
